/* This file is generated by 'dumpbmp', do not edit manually. */

#include <string.h>

#include <minigui/common.h>
#include <minigui/gdi.h>

#include "res_hash.h"

extern PMP_RES_HASH_UNIT __pmp_res_desktop_tip_gif;
extern PMP_RES_HASH_UNIT __pmp_res_desktop_selected_rec_gif;
extern PMP_RES_HASH_UNIT __pmp_res_desktop_calendar_png;
extern PMP_RES_HASH_UNIT __pmp_res_desktop_ebook_png;
extern PMP_RES_HASH_UNIT __pmp_res_desktop_picture_png;
extern PMP_RES_HASH_UNIT __pmp_res_public_folder_png;
extern PMP_RES_HASH_UNIT __pmp_res_desktop_radio_png;
extern PMP_RES_HASH_UNIT __pmp_res_menu_menu_top_gif;
extern PMP_RES_HASH_UNIT __pmp_res_desktop_worm_png;
extern PMP_RES_HASH_UNIT __pmp_res_menu_menu_btm_gif;
extern PMP_RES_HASH_UNIT __pmp_res_captionbar_bk_gif;
extern PMP_RES_HASH_UNIT __pmp_res_menu_menu_captbg_gif;
extern PMP_RES_HASH_UNIT __pmp_res_desktop_recorder_png;
extern PMP_RES_HASH_UNIT __pmp_res_desktop_calc_png;
extern PMP_RES_HASH_UNIT __pmp_res_desktop_video_png;
extern PMP_RES_HASH_UNIT __pmp_res_desktop_bk_gif;
extern PMP_RES_HASH_UNIT __pmp_res_captionbar_power_png;
extern PMP_RES_HASH_UNIT __pmp_res_menu_menu_mid_gif;
extern PMP_RES_HASH_UNIT __pmp_res_menu_menu_body_gif;
extern PMP_RES_HASH_UNIT __pmp_res_captionbar_logo_png;
extern PMP_RES_HASH_UNIT __pmp_res_desktop_stopwatch_png;
extern PMP_RES_HASH_UNIT __pmp_res_desktop_setup_png;
extern PMP_RES_HASH_UNIT __pmp_res_desktop_music_png;
extern PMP_RES_HASH_UNIT __pmp_res_desktop_housekeeper_png;
extern PMP_RES_HASH_UNIT __pmp_res_public_bg_gif;
extern PMP_RES_HASH_UNIT __pmp_res_desktop_russia_png;

static struct _PMP_RES_HASH_ENTRY
{
    int nr_keys;
    PMP_RES_HASH_UNIT *image[MAX_DUP_KEYS];
} PMP_RES_HASH_TABLE [NR_HASH_ENTRIES] = {
    {0, {}},
    {2, {&__pmp_res_desktop_tip_gif, &__pmp_res_desktop_selected_rec_gif, }},
    {4, {&__pmp_res_desktop_calendar_png, &__pmp_res_desktop_ebook_png, &__pmp_res_desktop_picture_png, &__pmp_res_public_folder_png, }},
    {2, {&__pmp_res_desktop_radio_png, &__pmp_res_menu_menu_top_gif, }},
    {0, {}},
    {0, {}},
    {3, {&__pmp_res_desktop_worm_png, &__pmp_res_menu_menu_btm_gif, &__pmp_res_captionbar_bk_gif, }},
    {0, {}},
    {1, {&__pmp_res_menu_menu_captbg_gif, }},
    {0, {}},
    {2, {&__pmp_res_desktop_recorder_png, &__pmp_res_desktop_calc_png, }},
    {3, {&__pmp_res_desktop_video_png, &__pmp_res_desktop_bk_gif, &__pmp_res_captionbar_power_png, }},
    {0, {}},
    {1, {&__pmp_res_menu_menu_mid_gif, }},
    {2, {&__pmp_res_menu_menu_body_gif, &__pmp_res_captionbar_logo_png, }},
    {2, {&__pmp_res_desktop_stopwatch_png, &__pmp_res_desktop_setup_png, }},
    {0, {}},
    {1, {&__pmp_res_desktop_music_png, }},
    {2, {&__pmp_res_desktop_housekeeper_png, &__pmp_res_public_bg_gif, }},
    {1, {&__pmp_res_desktop_russia_png, }},
};

static int _hash_string (const char* key)
{
    int hval;
    const char* ptr = (const char*) key;
    char c;
    int i;

    hval = 0;
    for (i = 1; (c = *ptr++); i++)
        hval += c * i;

    return (hval % NR_HASH_ENTRIES);
}

PMP_RES_HASH_UNIT* pmp_res_hash_retrive_unit (const char* path)
{
    struct _PMP_RES_HASH_ENTRY* entry;
    int hval = _hash_string (path);
    int i;

    entry = PMP_RES_HASH_TABLE + hval;
    for (i = 0; i < entry->nr_keys; i++) {
        if (strcmp (entry->image[i]->key, path) == 0) {
            return entry->image[i];
        }
    }

    return NULL;
}

